from lxml import etree
pooutput = """<?xml version="1.0" encoding="ISO-8859-1"?>
<nc:rpc-reply xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns="http://www.cisco.com/nxos:1.0:eth_pcm_dc3" message-id="463472">
 <nc:data>
  <show>
   <port-channel>
    <summary>
     <__XML__OPT_Cmd_show_port_channel_summary_interface>
      <__XML__OPT_Cmd_show_port_channel_summary___readonly__>
       <__readonly__>
        <TABLE_channel>
         <ROW_channel>
          <group>1</group>
          <port-channel>port-channel1</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet1/31</port>
            <port-status>P</port-status>
           </ROW_member>
           <ROW_member>
            <port>Ethernet1/32</port>
            <port-status>P</port-status>
           </ROW_member>
           <ROW_member>
            <port>Ethernet2/6</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>2</group>
          <port-channel>port-channel2</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet2/1</port>
            <port-status>P</port-status>
           </ROW_member>
           <ROW_member>
            <port>Ethernet2/2</port>
            <port-status>P</port-status>
           </ROW_member>
           <ROW_member>
            <port>Ethernet2/3</port>
            <port-status>P</port-status>
           </ROW_member>
           <ROW_member>
            <port>Ethernet2/4</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>10</group>
          <port-channel>port-channel10</port-channel>
          <layer>S</layer>
          <status>D</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet103/1/2</port>
            <port-status>D</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>11</group>
          <port-channel>port-channel11</port-channel>
          <layer>S</layer>
          <status>D</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet103/1/4</port>
            <port-status>D</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>12</group>
          <port-channel>port-channel12</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet102/1/1</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>13</group>
          <port-channel>port-channel13</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet102/1/3</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>14</group>
          <port-channel>port-channel14</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet102/1/5</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>15</group>
          <port-channel>port-channel15</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet102/1/7</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>16</group>
          <port-channel>port-channel16</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet102/1/9</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>17</group>
          <port-channel>port-channel17</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet103/1/9</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>18</group>
          <port-channel>port-channel18</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet103/1/10</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>19</group>
          <port-channel>port-channel19</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet103/1/11</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>20</group>
          <port-channel>port-channel20</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet103/1/12</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>21</group>
          <port-channel>port-channel21</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet103/1/13</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>22</group>
          <port-channel>port-channel22</port-channel>
          <layer>S</layer>
          <status>D</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet104/1/2</port>
            <port-status>D</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>23</group>
          <port-channel>port-channel23</port-channel>
          <layer>S</layer>
          <status>D</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet104/1/4</port>
            <port-status>D</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>24</group>
          <port-channel>port-channel24</port-channel>
          <layer>S</layer>
          <status>D</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet109/1/9</port>
            <port-status>I</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>25</group>
          <port-channel>port-channel25</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet109/1/10</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>26</group>
          <port-channel>port-channel26</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet110/1/4</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>27</group>
          <port-channel>port-channel27</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet110/1/2</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>28</group>
          <port-channel>port-channel28</port-channel>
          <layer>S</layer>
          <status>D</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet100/1/23</port>
            <port-status>I</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>29</group>
          <port-channel>port-channel29</port-channel>
          <layer>S</layer>
          <status>D</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet100/1/21</port>
            <port-status>I</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>100</group>
          <port-channel>port-channel100</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>NONE</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet1/1</port>
            <port-status>P</port-status>
           </ROW_member>
           <ROW_member>
            <port>Ethernet1/2</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>101</group>
          <port-channel>port-channel101</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>NONE</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet1/3</port>
            <port-status>P</port-status>
           </ROW_member>
           <ROW_member>
            <port>Ethernet1/4</port>
            <port-status>P</port-status>
           </ROW_member>
           <ROW_member>
            <port>Ethernet1/5</port>
            <port-status>P</port-status>
           </ROW_member>
           <ROW_member>
            <port>Ethernet1/6</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>102</group>
          <port-channel>port-channel102</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>NONE</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet1/7</port>
            <port-status>P</port-status>
           </ROW_member>
           <ROW_member>
            <port>Ethernet1/8</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>103</group>
          <port-channel>port-channel103</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>NONE</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet1/9</port>
            <port-status>P</port-status>
           </ROW_member>
           <ROW_member>
            <port>Ethernet1/10</port>
            <port-status>P</port-status>
           </ROW_member>
           <ROW_member>
            <port>Ethernet1/11</port>
            <port-status>P</port-status>
           </ROW_member>
           <ROW_member>
            <port>Ethernet1/12</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>104</group>
          <port-channel>port-channel104</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>NONE</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet1/13</port>
            <port-status>P</port-status>
           </ROW_member>
           <ROW_member>
            <port>Ethernet1/14</port>
            <port-status>P</port-status>
           </ROW_member>
           <ROW_member>
            <port>Ethernet1/15</port>
            <port-status>P</port-status>
           </ROW_member>
           <ROW_member>
            <port>Ethernet1/16</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>105</group>
          <port-channel>port-channel105</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>NONE</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet1/17</port>
            <port-status>P</port-status>
           </ROW_member>
           <ROW_member>
            <port>Ethernet1/18</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>106</group>
          <port-channel>port-channel106</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>NONE</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet1/19</port>
            <port-status>P</port-status>
           </ROW_member>
           <ROW_member>
            <port>Ethernet1/20</port>
            <port-status>P</port-status>
           </ROW_member>
           <ROW_member>
            <port>Ethernet1/21</port>
            <port-status>P</port-status>
           </ROW_member>
           <ROW_member>
            <port>Ethernet1/22</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>107</group>
          <port-channel>port-channel107</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>NONE</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet2/7</port>
            <port-status>P</port-status>
           </ROW_member>
           <ROW_member>
            <port>Ethernet2/8</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>108</group>
          <port-channel>port-channel108</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>NONE</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet2/9</port>
            <port-status>P</port-status>
           </ROW_member>
           <ROW_member>
            <port>Ethernet2/10</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>109</group>
          <port-channel>port-channel109</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>NONE</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet1/23</port>
            <port-status>P</port-status>
           </ROW_member>
           <ROW_member>
            <port>Ethernet1/24</port>
            <port-status>P</port-status>
           </ROW_member>
           <ROW_member>
            <port>Ethernet1/25</port>
            <port-status>P</port-status>
           </ROW_member>
           <ROW_member>
            <port>Ethernet1/26</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>110</group>
          <port-channel>port-channel110</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>NONE</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet1/27</port>
            <port-status>P</port-status>
           </ROW_member>
           <ROW_member>
            <port>Ethernet1/28</port>
            <port-status>P</port-status>
           </ROW_member>
           <ROW_member>
            <port>Ethernet1/29</port>
            <port-status>P</port-status>
           </ROW_member>
           <ROW_member>
            <port>Ethernet1/30</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>111</group>
          <port-channel>port-channel111</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>NONE</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet2/11</port>
            <port-status>P</port-status>
           </ROW_member>
           <ROW_member>
            <port>Ethernet2/12</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>203</group>
          <port-channel>port-channel203</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet102/1/35</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>204</group>
          <port-channel>port-channel204</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet102/1/33</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>205</group>
          <port-channel>port-channel205</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet102/1/31</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>206</group>
          <port-channel>port-channel206</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet102/1/29</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>207</group>
          <port-channel>port-channel207</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet102/1/27</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>208</group>
          <port-channel>port-channel208</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet102/1/25</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>209</group>
          <port-channel>port-channel209</port-channel>
          <layer>S</layer>
          <status>D</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet102/1/23</port>
            <port-status>I</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>210</group>
          <port-channel>port-channel210</port-channel>
          <layer>S</layer>
          <status>D</status>
          <type>Eth</type>
          <prtcl>NONE</prtcl>
         </ROW_channel>
         <ROW_channel>
          <group>211</group>
          <port-channel>port-channel211</port-channel>
          <layer>S</layer>
          <status>D</status>
          <type>Eth</type>
          <prtcl>NONE</prtcl>
         </ROW_channel>
         <ROW_channel>
          <group>212</group>
          <port-channel>port-channel212</port-channel>
          <layer>S</layer>
          <status>D</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet105/1/13</port>
            <port-status>D</port-status>
           </ROW_member>
           <ROW_member>
            <port>Ethernet105/1/14</port>
            <port-status>D</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>213</group>
          <port-channel>port-channel213</port-channel>
          <layer>S</layer>
          <status>D</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet105/1/15</port>
            <port-status>D</port-status>
           </ROW_member>
           <ROW_member>
            <port>Ethernet105/1/16</port>
            <port-status>D</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>214</group>
          <port-channel>port-channel214</port-channel>
          <layer>S</layer>
          <status>D</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet105/1/25</port>
            <port-status>D</port-status>
           </ROW_member>
           <ROW_member>
            <port>Ethernet105/1/26</port>
            <port-status>D</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>215</group>
          <port-channel>port-channel215</port-channel>
          <layer>S</layer>
          <status>D</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet105/1/27</port>
            <port-status>D</port-status>
           </ROW_member>
           <ROW_member>
            <port>Ethernet105/1/28</port>
            <port-status>D</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>216</group>
          <port-channel>port-channel216</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet107/1/45</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>217</group>
          <port-channel>port-channel217</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet108/1/45</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>218</group>
          <port-channel>port-channel218</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet107/1/46</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>219</group>
          <port-channel>port-channel219</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet108/1/46</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>220</group>
          <port-channel>port-channel220</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet107/1/47</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>221</group>
          <port-channel>port-channel221</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet108/1/47</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>222</group>
          <port-channel>port-channel222</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet107/1/48</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>223</group>
          <port-channel>port-channel223</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet108/1/48</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>224</group>
          <port-channel>port-channel224</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet107/1/41</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>225</group>
          <port-channel>port-channel225</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet108/1/41</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>226</group>
          <port-channel>port-channel226</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet107/1/42</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>227</group>
          <port-channel>port-channel227</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet108/1/42</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>228</group>
          <port-channel>port-channel228</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet107/1/43</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>229</group>
          <port-channel>port-channel229</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet108/1/43</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>230</group>
          <port-channel>port-channel230</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet107/1/44</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>231</group>
          <port-channel>port-channel231</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet108/1/44</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>232</group>
          <port-channel>port-channel232</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet107/1/37</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>233</group>
          <port-channel>port-channel233</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet108/1/37</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>234</group>
          <port-channel>port-channel234</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet107/1/38</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>235</group>
          <port-channel>port-channel235</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet108/1/38</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>236</group>
          <port-channel>port-channel236</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet107/1/39</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>237</group>
          <port-channel>port-channel237</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet108/1/39</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>238</group>
          <port-channel>port-channel238</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet107/1/40</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>239</group>
          <port-channel>port-channel239</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet108/1/40</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>240</group>
          <port-channel>port-channel240</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet107/1/33</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>241</group>
          <port-channel>port-channel241</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet108/1/33</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>242</group>
          <port-channel>port-channel242</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet107/1/34</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>243</group>
          <port-channel>port-channel243</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet108/1/34</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>244</group>
          <port-channel>port-channel244</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet107/1/35</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>245</group>
          <port-channel>port-channel245</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet108/1/35</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>246</group>
          <port-channel>port-channel246</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet107/1/36</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>247</group>
          <port-channel>port-channel247</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet108/1/36</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>248</group>
          <port-channel>port-channel248</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet107/1/29</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>249</group>
          <port-channel>port-channel249</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet108/1/29</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>250</group>
          <port-channel>port-channel250</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet107/1/30</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>251</group>
          <port-channel>port-channel251</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet108/1/30</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>252</group>
          <port-channel>port-channel252</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet107/1/31</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>253</group>
          <port-channel>port-channel253</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet108/1/31</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>254</group>
          <port-channel>port-channel254</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet107/1/32</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>255</group>
          <port-channel>port-channel255</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet108/1/32</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>256</group>
          <port-channel>port-channel256</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet107/1/25</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>257</group>
          <port-channel>port-channel257</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet108/1/25</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>258</group>
          <port-channel>port-channel258</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet107/1/26</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>259</group>
          <port-channel>port-channel259</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet108/1/26</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>260</group>
          <port-channel>port-channel260</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet107/1/27</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>261</group>
          <port-channel>port-channel261</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet108/1/27</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>262</group>
          <port-channel>port-channel262</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet107/1/28</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>263</group>
          <port-channel>port-channel263</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet108/1/28</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>264</group>
          <port-channel>port-channel264</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet107/1/21</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>265</group>
          <port-channel>port-channel265</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet108/1/21</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>266</group>
          <port-channel>port-channel266</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet107/1/22</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>267</group>
          <port-channel>port-channel267</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet108/1/22</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>268</group>
          <port-channel>port-channel268</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet107/1/23</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>269</group>
          <port-channel>port-channel269</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet108/1/23</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>270</group>
          <port-channel>port-channel270</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet107/1/24</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>271</group>
          <port-channel>port-channel271</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet108/1/24</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>272</group>
          <port-channel>port-channel272</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet107/1/17</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>273</group>
          <port-channel>port-channel273</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet108/1/17</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>274</group>
          <port-channel>port-channel274</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet107/1/18</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>275</group>
          <port-channel>port-channel275</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet108/1/18</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>276</group>
          <port-channel>port-channel276</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet107/1/19</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>277</group>
          <port-channel>port-channel277</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet108/1/19</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>278</group>
          <port-channel>port-channel278</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet107/1/20</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>279</group>
          <port-channel>port-channel279</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet108/1/20</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>280</group>
          <port-channel>port-channel280</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet107/1/13</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>281</group>
          <port-channel>port-channel281</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet108/1/13</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>282</group>
          <port-channel>port-channel282</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet107/1/14</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>283</group>
          <port-channel>port-channel283</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet108/1/14</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>284</group>
          <port-channel>port-channel284</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet107/1/15</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>285</group>
          <port-channel>port-channel285</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet108/1/15</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>286</group>
          <port-channel>port-channel286</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet107/1/16</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>287</group>
          <port-channel>port-channel287</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet108/1/16</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>288</group>
          <port-channel>port-channel288</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet107/1/9</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>289</group>
          <port-channel>port-channel289</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet108/1/9</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>290</group>
          <port-channel>port-channel290</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet107/1/10</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>291</group>
          <port-channel>port-channel291</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet108/1/10</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>292</group>
          <port-channel>port-channel292</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet107/1/11</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>293</group>
          <port-channel>port-channel293</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet108/1/11</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>294</group>
          <port-channel>port-channel294</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet107/1/12</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>295</group>
          <port-channel>port-channel295</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet108/1/12</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>296</group>
          <port-channel>port-channel296</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet107/1/5</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>297</group>
          <port-channel>port-channel297</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet108/1/5</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>298</group>
          <port-channel>port-channel298</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet107/1/6</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>299</group>
          <port-channel>port-channel299</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet108/1/6</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>300</group>
          <port-channel>port-channel300</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet107/1/7</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>301</group>
          <port-channel>port-channel301</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet108/1/7</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>302</group>
          <port-channel>port-channel302</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet107/1/8</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>303</group>
          <port-channel>port-channel303</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet108/1/8</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>304</group>
          <port-channel>port-channel304</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet107/1/1</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>305</group>
          <port-channel>port-channel305</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet108/1/1</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>306</group>
          <port-channel>port-channel306</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet107/1/2</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>307</group>
          <port-channel>port-channel307</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet108/1/2</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>308</group>
          <port-channel>port-channel308</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet107/1/3</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>309</group>
          <port-channel>port-channel309</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet108/1/3</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>316</group>
          <port-channel>port-channel316</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet107/1/4</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>317</group>
          <port-channel>port-channel317</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet108/1/4</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>318</group>
          <port-channel>port-channel318</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet103/1/8</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>319</group>
          <port-channel>port-channel319</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet103/1/21</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>320</group>
          <port-channel>port-channel320</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet103/1/22</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>321</group>
          <port-channel>port-channel321</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet103/1/23</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>322</group>
          <port-channel>port-channel322</port-channel>
          <layer>S</layer>
          <status>D</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet103/1/24</port>
            <port-status>D</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>323</group>
          <port-channel>port-channel323</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet103/1/25</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
         <ROW_channel>
          <group>324</group>
          <port-channel>port-channel324</port-channel>
          <layer>S</layer>
          <status>U</status>
          <type>Eth</type>
          <prtcl>LACP</prtcl>
          <TABLE_member>
           <ROW_member>
            <port>Ethernet103/1/26</port>
            <port-status>P</port-status>
           </ROW_member>
          </TABLE_member>
         </ROW_channel>
        </TABLE_channel>
       </__readonly__>
      </__XML__OPT_Cmd_show_port_channel_summary___readonly__>
     </__XML__OPT_Cmd_show_port_channel_summary_interface>
    </summary>
   </port-channel>
  </show>
 </nc:data>
</nc:rpc-reply>
"""

def parse_get_nsmap(parsed_doc):
    """

    @param parsed_doc:
    """
    nsdict = parsed_doc.nsmap
    if 'mod' in nsdict:
        return "{{{}}}".format(nsdict['mod'])
    elif None in nsdict:
        return "{{{}}}".format(nsdict[None])
    else:
        return ''

parser = etree.XMLParser(remove_blank_text=True)
intposummparsed = etree.fromstring(pooutput, parser=parser)
ethpcmdc3schema = parse_get_nsmap(intposummparsed)

portchannel = {}
for element in intposummparsed.iter("{}ROW_channel".format(ethpcmdc3schema)):
    elelist = [i.tag for i in list(element)]
    group = element.find("{}group".format(ethpcmdc3schema)).text
    point = element.find("{}port-channel".format(ethpcmdc3schema)).text
    portchannel[point] = {'group': group}
    portchannel[point]['polayer'] = element.find("{}layer".format(ethpcmdc3schema)).text
    portchannel[point]['postatus'] = element.find("{}status".format(ethpcmdc3schema)).text
    portchannel[point]['poprotocol'] = element.find("{}prtcl".format(ethpcmdc3schema)).text
    if "{}TABLE_member".format(ethpcmdc3schema) in elelist:
        interfaces = element.find("{}TABLE_member".format(ethpcmdc3schema))
        ports = []
        for i in interfaces.iter("{}ROW_member".format(ethpcmdc3schema)):
            ints = i.find("{}port".format(ethpcmdc3schema))
            ports.append(ints.text)
            portchannel[ints.text] = {'portchannel': point}
            portstatus = i.find("{}port-status".format(ethpcmdc3schema))
            portchannel[ints.text]['postatus'] = portstatus.text
        portchannel[point]['ports'] = ports

